import { Menu } from "@shared/schema";

export const menuDatabase: Menu[] = [
  { id: "m001", canonicalName: "kimchi-jjigae", displayName: "김치찌개", cuisine: "korean", base: "rice", hasSoup: true, protein: "pork", spicyLevel: 2, heavyLevel: 2, priceRange: "low", synonyms: ["김찌"] },
  { id: "m002", canonicalName: "doenjang-jjigae", displayName: "된장찌개", cuisine: "korean", base: "rice", hasSoup: true, protein: "mixed", spicyLevel: 0, heavyLevel: 2, priceRange: "low", synonyms: ["된찌"] },
  { id: "m003", canonicalName: "sundubu-jjigae", displayName: "순두부찌개", cuisine: "korean", base: "rice", hasSoup: true, protein: "seafood", spicyLevel: 2, heavyLevel: 2, priceRange: "low" },
  { id: "m004", canonicalName: "budae-jjigae", displayName: "부대찌개", cuisine: "korean", base: "rice", hasSoup: true, protein: "mixed", spicyLevel: 2, heavyLevel: 3, priceRange: "medium" },
  { id: "m005", canonicalName: "samgyetang", displayName: "삼계탕", cuisine: "korean", base: "rice", hasSoup: true, protein: "chicken", spicyLevel: 0, heavyLevel: 3, priceRange: "high" },
  { id: "m006", canonicalName: "seolleongtang", displayName: "설렁탕", cuisine: "korean", base: "rice", hasSoup: true, protein: "beef", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m007", canonicalName: "galbitang", displayName: "갈비탕", cuisine: "korean", base: "rice", hasSoup: true, protein: "beef", spicyLevel: 0, heavyLevel: 3, priceRange: "high" },
  { id: "m008", canonicalName: "yukgaejang", displayName: "육개장", cuisine: "korean", base: "rice", hasSoup: true, protein: "beef", spicyLevel: 3, heavyLevel: 2, priceRange: "medium" },
  { id: "m009", canonicalName: "gamjatang", displayName: "감자탕", cuisine: "korean", base: "rice", hasSoup: true, protein: "pork", spicyLevel: 2, heavyLevel: 3, priceRange: "medium" },
  { id: "m010", canonicalName: "kongnamul-gukbap", displayName: "콩나물국밥", cuisine: "korean", base: "rice", hasSoup: true, protein: "mixed", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },

  { id: "m011", canonicalName: "bibimbap", displayName: "비빔밥", cuisine: "korean", base: "rice", hasSoup: false, protein: "mixed", spicyLevel: 1, heavyLevel: 2, priceRange: "low" },
  { id: "m012", canonicalName: "dolsot-bibimbap", displayName: "돌솥비빔밥", cuisine: "korean", base: "rice", hasSoup: false, protein: "mixed", spicyLevel: 1, heavyLevel: 2, priceRange: "medium" },
  { id: "m013", canonicalName: "bulgogi", displayName: "불고기", cuisine: "korean", base: "rice", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m014", canonicalName: "galbi", displayName: "갈비", cuisine: "korean", base: "rice", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 3, priceRange: "high" },
  { id: "m015", canonicalName: "samgyeopsal", displayName: "삼겹살", cuisine: "korean", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m016", canonicalName: "jeyuk-bokkeum", displayName: "제육볶음", cuisine: "korean", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 2, heavyLevel: 2, priceRange: "low" },
  { id: "m017", canonicalName: "dakgalbi", displayName: "닭갈비", cuisine: "korean", base: "rice", hasSoup: false, protein: "chicken", spicyLevel: 2, heavyLevel: 2, priceRange: "medium" },
  { id: "m018", canonicalName: "bossam", displayName: "보쌈", cuisine: "korean", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m019", canonicalName: "jokbal", displayName: "족발", cuisine: "korean", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m020", canonicalName: "gopchang", displayName: "곱창", cuisine: "korean", base: "rice", hasSoup: false, protein: "beef", spicyLevel: 1, heavyLevel: 3, priceRange: "high" },

  { id: "m021", canonicalName: "japchae", displayName: "잡채", cuisine: "korean", base: "noodle", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m022", canonicalName: "kalguksu", displayName: "칼국수", cuisine: "korean", base: "noodle", hasSoup: true, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m023", canonicalName: "naengmyeon", displayName: "냉면", cuisine: "korean", base: "noodle", hasSoup: true, protein: "beef", spicyLevel: 1, heavyLevel: 1, priceRange: "medium" },
  { id: "m024", canonicalName: "bibim-naengmyeon", displayName: "비빔냉면", cuisine: "korean", base: "noodle", hasSoup: false, protein: "beef", spicyLevel: 2, heavyLevel: 1, priceRange: "medium" },
  { id: "m025", canonicalName: "sujebi", displayName: "수제비", cuisine: "korean", base: "noodle", hasSoup: true, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m026", canonicalName: "jjolmyeon", displayName: "쫄면", cuisine: "korean", base: "noodle", hasSoup: false, protein: "vegetarian", spicyLevel: 2, heavyLevel: 1, priceRange: "low" },
  { id: "m027", canonicalName: "kongguksu", displayName: "콩국수", cuisine: "korean", base: "noodle", hasSoup: true, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "medium" },

  { id: "m028", canonicalName: "jjajangmyeon", displayName: "짜장면", cuisine: "chinese", base: "noodle", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m029", canonicalName: "jjamppong", displayName: "짬뽕", cuisine: "chinese", base: "noodle", hasSoup: true, protein: "seafood", spicyLevel: 2, heavyLevel: 2, priceRange: "low" },
  { id: "m030", canonicalName: "tangsuyuk", displayName: "탕수육", cuisine: "chinese", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m031", canonicalName: "mapa-tofu", displayName: "마파두부", cuisine: "chinese", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 2, heavyLevel: 2, priceRange: "medium" },
  { id: "m032", canonicalName: "gganpungi", displayName: "깐풍기", cuisine: "chinese", base: "rice", hasSoup: false, protein: "chicken", spicyLevel: 1, heavyLevel: 2, priceRange: "medium" },
  { id: "m033", canonicalName: "yuxiang-roussi", displayName: "유산슬", cuisine: "chinese", base: "rice", hasSoup: false, protein: "mixed", spicyLevel: 0, heavyLevel: 2, priceRange: "high" },
  { id: "m034", canonicalName: "jjamppong-bap", displayName: "짬뽕밥", cuisine: "chinese", base: "rice", hasSoup: true, protein: "seafood", spicyLevel: 2, heavyLevel: 2, priceRange: "low" },
  { id: "m035", canonicalName: "samseon-jjajang", displayName: "삼선짜장", cuisine: "chinese", base: "noodle", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m036", canonicalName: "yangnyeom-gopchang", displayName: "양장피", cuisine: "chinese", base: "other", hasSoup: false, protein: "mixed", spicyLevel: 1, heavyLevel: 2, priceRange: "high" },
  { id: "m037", canonicalName: "gun-mandoo", displayName: "군만두", cuisine: "chinese", base: "other", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },

  { id: "m038", canonicalName: "ramen", displayName: "라멘", cuisine: "japanese", base: "noodle", hasSoup: true, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m039", canonicalName: "tonkotsu-ramen", displayName: "돈코츠라멘", cuisine: "japanese", base: "noodle", hasSoup: true, protein: "pork", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m040", canonicalName: "shoyu-ramen", displayName: "쇼유라멘", cuisine: "japanese", base: "noodle", hasSoup: true, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m041", canonicalName: "miso-ramen", displayName: "미소라멘", cuisine: "japanese", base: "noodle", hasSoup: true, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m042", canonicalName: "udon", displayName: "우동", cuisine: "japanese", base: "noodle", hasSoup: true, protein: "mixed", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m043", canonicalName: "soba", displayName: "소바", cuisine: "japanese", base: "noodle", hasSoup: true, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "medium" },
  { id: "m044", canonicalName: "sushi", displayName: "초밥", cuisine: "japanese", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "high" },
  { id: "m045", canonicalName: "chirashi", displayName: "치라시", cuisine: "japanese", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "high" },
  { id: "m046", canonicalName: "donburi", displayName: "덮밥", cuisine: "japanese", base: "rice", hasSoup: false, protein: "mixed", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m047", canonicalName: "katsudon", displayName: "카츠동", cuisine: "japanese", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m048", canonicalName: "oyakodon", displayName: "오야코동", cuisine: "japanese", base: "rice", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m049", canonicalName: "gyudon", displayName: "규동", cuisine: "japanese", base: "rice", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m050", canonicalName: "curry-rice", displayName: "카레라이스", cuisine: "japanese", base: "rice", hasSoup: false, protein: "mixed", spicyLevel: 1, heavyLevel: 2, priceRange: "low" },
  { id: "m051", canonicalName: "tonkatsu", displayName: "돈까스", cuisine: "japanese", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m052", canonicalName: "katsu-curry", displayName: "카츠카레", cuisine: "japanese", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 1, heavyLevel: 3, priceRange: "medium" },
  { id: "m053", canonicalName: "takoyaki", displayName: "타코야끼", cuisine: "japanese", base: "other", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },
  { id: "m054", canonicalName: "okonomiyaki", displayName: "오꼬노미야끼", cuisine: "japanese", base: "other", hasSoup: false, protein: "mixed", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m055", canonicalName: "tempura", displayName: "텐동", cuisine: "japanese", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },

  { id: "m056", canonicalName: "pasta-cream", displayName: "크림파스타", cuisine: "western", base: "noodle", hasSoup: false, protein: "mixed", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m057", canonicalName: "pasta-tomato", displayName: "토마토파스타", cuisine: "western", base: "noodle", hasSoup: false, protein: "mixed", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m058", canonicalName: "pasta-aglio", displayName: "알리오올리오", cuisine: "western", base: "noodle", hasSoup: false, protein: "seafood", spicyLevel: 1, heavyLevel: 1, priceRange: "medium" },
  { id: "m059", canonicalName: "pasta-carbonara", displayName: "카르보나라", cuisine: "western", base: "noodle", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m060", canonicalName: "pasta-rose", displayName: "로제파스타", cuisine: "western", base: "noodle", hasSoup: false, protein: "mixed", spicyLevel: 1, heavyLevel: 2, priceRange: "medium" },
  { id: "m061", canonicalName: "pasta-vongole", displayName: "봉골레파스타", cuisine: "western", base: "noodle", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m062", canonicalName: "pizza-margherita", displayName: "마르게리타피자", cuisine: "western", base: "bread", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m063", canonicalName: "pizza-pepperoni", displayName: "페퍼로니피자", cuisine: "western", base: "bread", hasSoup: false, protein: "pork", spicyLevel: 1, heavyLevel: 3, priceRange: "medium" },
  { id: "m064", canonicalName: "pizza-hawaiian", displayName: "하와이안피자", cuisine: "western", base: "bread", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m065", canonicalName: "pizza-combination", displayName: "콤비네이션피자", cuisine: "western", base: "bread", hasSoup: false, protein: "mixed", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m066", canonicalName: "steak", displayName: "스테이크", cuisine: "western", base: "other", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 3, priceRange: "high" },
  { id: "m067", canonicalName: "hamburger", displayName: "햄버거", cuisine: "western", base: "bread", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 3, priceRange: "low" },
  { id: "m068", canonicalName: "risotto", displayName: "리조또", cuisine: "western", base: "rice", hasSoup: false, protein: "mixed", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m069", canonicalName: "lasagna", displayName: "라자냐", cuisine: "western", base: "noodle", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m070", canonicalName: "fish-and-chips", displayName: "피쉬앤칩스", cuisine: "western", base: "other", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m071", canonicalName: "chicken-salad", displayName: "치킨샐러드", cuisine: "western", base: "salad", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 1, priceRange: "medium" },
  { id: "m072", canonicalName: "caesar-salad", displayName: "시저샐러드", cuisine: "western", base: "salad", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 1, priceRange: "medium" },
  { id: "m073", canonicalName: "grilled-chicken", displayName: "그릴드치킨", cuisine: "western", base: "other", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m074", canonicalName: "omelet-rice", displayName: "오므라이스", cuisine: "western", base: "rice", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m075", canonicalName: "club-sandwich", displayName: "클럽샌드위치", cuisine: "western", base: "bread", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },

  { id: "m076", canonicalName: "ramyeon", displayName: "라면", cuisine: "bunsik", base: "noodle", hasSoup: true, protein: "vegetarian", spicyLevel: 2, heavyLevel: 1, priceRange: "low" },
  { id: "m077", canonicalName: "cheese-ramyeon", displayName: "치즈라면", cuisine: "bunsik", base: "noodle", hasSoup: true, protein: "vegetarian", spicyLevel: 2, heavyLevel: 2, priceRange: "low" },
  { id: "m078", canonicalName: "tteokbokki", displayName: "떡볶이", cuisine: "bunsik", base: "other", hasSoup: false, protein: "vegetarian", spicyLevel: 2, heavyLevel: 2, priceRange: "low" },
  { id: "m079", canonicalName: "rabokki", displayName: "라볶이", cuisine: "bunsik", base: "noodle", hasSoup: false, protein: "vegetarian", spicyLevel: 2, heavyLevel: 2, priceRange: "low" },
  { id: "m080", canonicalName: "sundae", displayName: "순대", cuisine: "bunsik", base: "other", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m081", canonicalName: "gimbap", displayName: "김밥", cuisine: "bunsik", base: "rice", hasSoup: false, protein: "mixed", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },
  { id: "m082", canonicalName: "chungmu-gimbap", displayName: "충무김밥", cuisine: "bunsik", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 1, heavyLevel: 1, priceRange: "low" },
  { id: "m083", canonicalName: "twigim", displayName: "튀김", cuisine: "bunsik", base: "other", hasSoup: false, protein: "mixed", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m084", canonicalName: "odeng", displayName: "오뎅", cuisine: "bunsik", base: "other", hasSoup: true, protein: "seafood", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },
  { id: "m085", canonicalName: "mandu", displayName: "만두", cuisine: "bunsik", base: "other", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m086", canonicalName: "ramyeon-gimbap", displayName: "라면+김밥", cuisine: "bunsik", base: "noodle", hasSoup: true, protein: "mixed", spicyLevel: 2, heavyLevel: 2, priceRange: "low" },
  { id: "m087", canonicalName: "sundae-gukbap", displayName: "순대국밥", cuisine: "bunsik", base: "rice", hasSoup: true, protein: "pork", spicyLevel: 0, heavyLevel: 3, priceRange: "low" },
  { id: "m088", canonicalName: "cheolpan-bokkeum", displayName: "철판볶음밥", cuisine: "bunsik", base: "rice", hasSoup: false, protein: "mixed", spicyLevel: 1, heavyLevel: 2, priceRange: "low" },

  { id: "m089", canonicalName: "fried-chicken", displayName: "후라이드치킨", cuisine: "korean", base: "other", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m090", canonicalName: "yangnyeom-chicken", displayName: "양념치킨", cuisine: "korean", base: "other", hasSoup: false, protein: "chicken", spicyLevel: 1, heavyLevel: 3, priceRange: "medium" },
  { id: "m091", canonicalName: "padak", displayName: "파닭", cuisine: "korean", base: "other", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m092", canonicalName: "honey-chicken", displayName: "허니콤보", cuisine: "korean", base: "other", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },

  { id: "m093", canonicalName: "pho", displayName: "쌀국수", cuisine: "asian", base: "noodle", hasSoup: true, protein: "beef", spicyLevel: 0, heavyLevel: 1, priceRange: "medium" },
  { id: "m094", canonicalName: "bun-cha", displayName: "분짜", cuisine: "asian", base: "noodle", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m095", canonicalName: "pad-thai", displayName: "팟타이", cuisine: "asian", base: "noodle", hasSoup: false, protein: "seafood", spicyLevel: 1, heavyLevel: 2, priceRange: "medium" },
  { id: "m096", canonicalName: "tom-yum", displayName: "똠얌꿍", cuisine: "asian", base: "noodle", hasSoup: true, protein: "seafood", spicyLevel: 3, heavyLevel: 1, priceRange: "medium" },
  { id: "m097", canonicalName: "banh-mi", displayName: "반미", cuisine: "asian", base: "bread", hasSoup: false, protein: "pork", spicyLevel: 1, heavyLevel: 1, priceRange: "low" },
  { id: "m098", canonicalName: "green-curry", displayName: "그린커리", cuisine: "asian", base: "rice", hasSoup: true, protein: "chicken", spicyLevel: 2, heavyLevel: 2, priceRange: "medium" },
  { id: "m099", canonicalName: "massaman-curry", displayName: "마싸만커리", cuisine: "asian", base: "rice", hasSoup: true, protein: "chicken", spicyLevel: 1, heavyLevel: 2, priceRange: "medium" },
  { id: "m100", canonicalName: "nasi-goreng", displayName: "나시고랭", cuisine: "asian", base: "rice", hasSoup: false, protein: "mixed", spicyLevel: 1, heavyLevel: 2, priceRange: "medium" },

  { id: "m101", canonicalName: "guksu", displayName: "잔치국수", cuisine: "korean", base: "noodle", hasSoup: true, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },
  { id: "m102", canonicalName: "memil-guksu", displayName: "메밀국수", cuisine: "korean", base: "noodle", hasSoup: true, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },
  { id: "m103", canonicalName: "hwangtae-haejangguk", displayName: "황태해장국", cuisine: "korean", base: "rice", hasSoup: true, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m104", canonicalName: "haemul-tang", displayName: "해물탕", cuisine: "korean", base: "rice", hasSoup: true, protein: "seafood", spicyLevel: 2, heavyLevel: 2, priceRange: "high" },
  { id: "m105", canonicalName: "agujjim", displayName: "아구찜", cuisine: "korean", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 3, heavyLevel: 2, priceRange: "high" },
  { id: "m106", canonicalName: "ganjang-gejang", displayName: "간장게장", cuisine: "korean", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "high" },
  { id: "m107", canonicalName: "yangnyeom-gejang", displayName: "양념게장", cuisine: "korean", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 2, heavyLevel: 2, priceRange: "high" },
  { id: "m108", canonicalName: "jogae-gui", displayName: "조개구이", cuisine: "korean", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "high" },
  { id: "m109", canonicalName: "nakji-bokkeum", displayName: "낙지볶음", cuisine: "korean", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 3, heavyLevel: 2, priceRange: "medium" },
  { id: "m110", canonicalName: "ojingeo-bokkeum", displayName: "오징어볶음", cuisine: "korean", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 2, heavyLevel: 2, priceRange: "medium" },

  { id: "m111", canonicalName: "dak-doritang", displayName: "닭도리탕", cuisine: "korean", base: "rice", hasSoup: true, protein: "chicken", spicyLevel: 2, heavyLevel: 2, priceRange: "medium" },
  { id: "m112", canonicalName: "jjimdak", displayName: "찜닭", cuisine: "korean", base: "rice", hasSoup: false, protein: "chicken", spicyLevel: 1, heavyLevel: 2, priceRange: "medium" },
  { id: "m113", canonicalName: "dakbokkeumtang", displayName: "닭볶음탕", cuisine: "korean", base: "rice", hasSoup: true, protein: "chicken", spicyLevel: 2, heavyLevel: 2, priceRange: "medium" },

  { id: "m114", canonicalName: "kimchi-bokkeumbap", displayName: "김치볶음밥", cuisine: "korean", base: "rice", hasSoup: false, protein: "mixed", spicyLevel: 1, heavyLevel: 2, priceRange: "low" },
  { id: "m115", canonicalName: "haemul-bokkeumbap", displayName: "해물볶음밥", cuisine: "korean", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 1, heavyLevel: 2, priceRange: "medium" },
  { id: "m116", canonicalName: "sogogi-gukbap", displayName: "소고기국밥", cuisine: "korean", base: "rice", hasSoup: true, protein: "beef", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m117", canonicalName: "dwaeji-gukbap", displayName: "돼지국밥", cuisine: "korean", base: "rice", hasSoup: true, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },

  { id: "m118", canonicalName: "taco", displayName: "타코", cuisine: "western", base: "bread", hasSoup: false, protein: "beef", spicyLevel: 1, heavyLevel: 2, priceRange: "medium" },
  { id: "m119", canonicalName: "burrito", displayName: "부리또", cuisine: "western", base: "bread", hasSoup: false, protein: "beef", spicyLevel: 1, heavyLevel: 3, priceRange: "medium" },
  { id: "m120", canonicalName: "quesadilla", displayName: "퀘사디아", cuisine: "western", base: "bread", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m121", canonicalName: "nachos", displayName: "나초", cuisine: "western", base: "other", hasSoup: false, protein: "beef", spicyLevel: 1, heavyLevel: 2, priceRange: "medium" },

  { id: "m122", canonicalName: "poke-bowl", displayName: "포케", cuisine: "western", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 1, priceRange: "medium" },
  { id: "m123", canonicalName: "acai-bowl", displayName: "아사이볼", cuisine: "western", base: "other", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "medium" },
  { id: "m124", canonicalName: "salmon-salad", displayName: "연어샐러드", cuisine: "western", base: "salad", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 1, priceRange: "high" },
  { id: "m125", canonicalName: "steak-salad", displayName: "스테이크샐러드", cuisine: "western", base: "salad", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 2, priceRange: "high" },

  { id: "m126", canonicalName: "teriyaki-chicken", displayName: "데리야끼치킨", cuisine: "japanese", base: "rice", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m127", canonicalName: "yakiniku", displayName: "야키니꾸", cuisine: "japanese", base: "rice", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 3, priceRange: "high" },
  { id: "m128", canonicalName: "sukiyaki", displayName: "스키야키", cuisine: "japanese", base: "rice", hasSoup: true, protein: "beef", spicyLevel: 0, heavyLevel: 3, priceRange: "high" },
  { id: "m129", canonicalName: "shabu-shabu", displayName: "샤브샤브", cuisine: "japanese", base: "noodle", hasSoup: true, protein: "beef", spicyLevel: 0, heavyLevel: 2, priceRange: "high" },
  { id: "m130", canonicalName: "karaage", displayName: "가라아게", cuisine: "japanese", base: "rice", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },

  { id: "m131", canonicalName: "yangchun-myeon", displayName: "양춘면", cuisine: "chinese", base: "noodle", hasSoup: true, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },
  { id: "m132", canonicalName: "ulmeyon", displayName: "울면", cuisine: "chinese", base: "noodle", hasSoup: true, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m133", canonicalName: "gogichuchapbap", displayName: "고기짜춘밥", cuisine: "chinese", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m134", canonicalName: "bokkeumbap", displayName: "볶음밥", cuisine: "chinese", base: "rice", hasSoup: false, protein: "mixed", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m135", canonicalName: "palbochae", displayName: "팔보채", cuisine: "chinese", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "high" },

  { id: "m136", canonicalName: "dwaeji-galbi", displayName: "돼지갈비", cuisine: "korean", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 1, heavyLevel: 3, priceRange: "medium" },
  { id: "m137", canonicalName: "chadol", displayName: "차돌박이", cuisine: "korean", base: "rice", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 3, priceRange: "high" },
  { id: "m138", canonicalName: "hanwoo", displayName: "한우", cuisine: "korean", base: "rice", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 3, priceRange: "high" },
  { id: "m139", canonicalName: "moksal", displayName: "목살", cuisine: "korean", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m140", canonicalName: "hangjeongsal", displayName: "항정살", cuisine: "korean", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },

  { id: "m141", canonicalName: "jjukkumi", displayName: "쭈꾸미볶음", cuisine: "korean", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 3, heavyLevel: 2, priceRange: "medium" },
  { id: "m142", canonicalName: "galchi-jorim", displayName: "갈치조림", cuisine: "korean", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 2, heavyLevel: 2, priceRange: "medium" },
  { id: "m143", canonicalName: "godeungeo-gui", displayName: "고등어구이", cuisine: "korean", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m144", canonicalName: "saeng-seon-gui", displayName: "생선구이", cuisine: "korean", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },

  { id: "m145", canonicalName: "hoe", displayName: "회", cuisine: "korean", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "high" },
  { id: "m146", canonicalName: "hoe-deopbap", displayName: "회덮밥", cuisine: "korean", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 1, heavyLevel: 2, priceRange: "medium" },
  { id: "m147", canonicalName: "mul-hoe", displayName: "물회", cuisine: "korean", base: "rice", hasSoup: true, protein: "seafood", spicyLevel: 2, heavyLevel: 1, priceRange: "medium" },

  { id: "m148", canonicalName: "tofu-kimchi", displayName: "두부김치", cuisine: "korean", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 1, heavyLevel: 2, priceRange: "low" },
  { id: "m149", canonicalName: "dubu-jorim", displayName: "두부조림", cuisine: "korean", base: "rice", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },
  { id: "m150", canonicalName: "gyeran-mari", displayName: "계란말이", cuisine: "korean", base: "rice", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },

  { id: "m151", canonicalName: "hot-dog", displayName: "핫도그", cuisine: "western", base: "bread", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m152", canonicalName: "corn-dog", displayName: "콘도그", cuisine: "bunsik", base: "bread", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m153", canonicalName: "egg-toast", displayName: "에그토스트", cuisine: "bunsik", base: "bread", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },

  { id: "m154", canonicalName: "bingsu", displayName: "빙수", cuisine: "korean", base: "other", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "medium" },
  { id: "m155", canonicalName: "hotteok", displayName: "호떡", cuisine: "bunsik", base: "bread", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m156", canonicalName: "bungeoppang", displayName: "붕어빵", cuisine: "bunsik", base: "bread", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },

  { id: "m157", canonicalName: "soonsal-chicken", displayName: "순살치킨", cuisine: "korean", base: "other", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m158", canonicalName: "buldak", displayName: "불닭", cuisine: "korean", base: "other", hasSoup: false, protein: "chicken", spicyLevel: 3, heavyLevel: 3, priceRange: "medium" },
  { id: "m159", canonicalName: "maratang", displayName: "마라탕", cuisine: "chinese", base: "noodle", hasSoup: true, protein: "mixed", spicyLevel: 3, heavyLevel: 2, priceRange: "medium" },
  { id: "m160", canonicalName: "mala-xiang-guo", displayName: "마라샹궈", cuisine: "chinese", base: "rice", hasSoup: false, protein: "mixed", spicyLevel: 3, heavyLevel: 2, priceRange: "medium" },

  { id: "m161", canonicalName: "shawarma", displayName: "샤와르마", cuisine: "western", base: "bread", hasSoup: false, protein: "chicken", spicyLevel: 1, heavyLevel: 2, priceRange: "medium" },
  { id: "m162", canonicalName: "falafel", displayName: "팔라펠", cuisine: "western", base: "bread", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "medium" },
  { id: "m163", canonicalName: "kebab", displayName: "케밥", cuisine: "western", base: "bread", hasSoup: false, protein: "beef", spicyLevel: 1, heavyLevel: 2, priceRange: "medium" },

  { id: "m164", canonicalName: "galbi-jjim", displayName: "갈비찜", cuisine: "korean", base: "rice", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 3, priceRange: "high" },
  { id: "m165", canonicalName: "braised-pork", displayName: "돼지갈비찜", cuisine: "korean", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },

  { id: "m166", canonicalName: "juk", displayName: "죽", cuisine: "korean", base: "rice", hasSoup: true, protein: "mixed", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },
  { id: "m167", canonicalName: "jeonbok-juk", displayName: "전복죽", cuisine: "korean", base: "rice", hasSoup: true, protein: "seafood", spicyLevel: 0, heavyLevel: 1, priceRange: "high" },
  { id: "m168", canonicalName: "hobak-juk", displayName: "호박죽", cuisine: "korean", base: "rice", hasSoup: true, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },

  { id: "m169", canonicalName: "chicken-wrap", displayName: "치킨랩", cuisine: "western", base: "bread", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m170", canonicalName: "bagel-sandwich", displayName: "베이글샌드위치", cuisine: "western", base: "bread", hasSoup: false, protein: "mixed", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },

  { id: "m171", canonicalName: "budae-jeongol", displayName: "부대전골", cuisine: "korean", base: "rice", hasSoup: true, protein: "mixed", spicyLevel: 2, heavyLevel: 3, priceRange: "medium" },
  { id: "m172", canonicalName: "gopchang-jeongol", displayName: "곱창전골", cuisine: "korean", base: "rice", hasSoup: true, protein: "beef", spicyLevel: 1, heavyLevel: 3, priceRange: "high" },
  { id: "m173", canonicalName: "haemul-jeongol", displayName: "해물전골", cuisine: "korean", base: "rice", hasSoup: true, protein: "seafood", spicyLevel: 2, heavyLevel: 2, priceRange: "high" },

  { id: "m174", canonicalName: "gyeranjjim", displayName: "계란찜", cuisine: "korean", base: "rice", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },
  { id: "m175", canonicalName: "haemulpajeon", displayName: "해물파전", cuisine: "korean", base: "other", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m176", canonicalName: "kimchijeon", displayName: "김치전", cuisine: "korean", base: "other", hasSoup: false, protein: "vegetarian", spicyLevel: 1, heavyLevel: 2, priceRange: "low" },
  { id: "m177", canonicalName: "pajeon", displayName: "파전", cuisine: "korean", base: "other", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },

  { id: "m178", canonicalName: "thai-fried-rice", displayName: "태국볶음밥", cuisine: "asian", base: "rice", hasSoup: false, protein: "chicken", spicyLevel: 1, heavyLevel: 2, priceRange: "medium" },
  { id: "m179", canonicalName: "spring-rolls", displayName: "스프링롤", cuisine: "asian", base: "other", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },
  { id: "m180", canonicalName: "satay", displayName: "사테", cuisine: "asian", base: "rice", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },

  { id: "m181", canonicalName: "egg-fried-rice", displayName: "계란볶음밥", cuisine: "chinese", base: "rice", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m182", canonicalName: "seafood-fried-rice", displayName: "해물볶음밥", cuisine: "chinese", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m183", canonicalName: "spicy-rice-cake", displayName: "궁중떡볶이", cuisine: "korean", base: "other", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m184", canonicalName: "cheese-tteokbokki", displayName: "치즈떡볶이", cuisine: "bunsik", base: "other", hasSoup: false, protein: "vegetarian", spicyLevel: 2, heavyLevel: 2, priceRange: "low" },

  { id: "m185", canonicalName: "beef-tartare", displayName: "육회", cuisine: "korean", base: "rice", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 2, priceRange: "high" },
  { id: "m186", canonicalName: "yukhoe-bibimbap", displayName: "육회비빔밥", cuisine: "korean", base: "rice", hasSoup: false, protein: "beef", spicyLevel: 1, heavyLevel: 2, priceRange: "high" },

  { id: "m187", canonicalName: "chicken-mayo-rice", displayName: "치킨마요", cuisine: "bunsik", base: "rice", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m188", canonicalName: "donkatsu-curry", displayName: "돈까스카레", cuisine: "japanese", base: "rice", hasSoup: false, protein: "pork", spicyLevel: 1, heavyLevel: 3, priceRange: "medium" },

  { id: "m189", canonicalName: "dim-sum", displayName: "딤섬", cuisine: "chinese", base: "other", hasSoup: false, protein: "mixed", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m190", canonicalName: "xiao-long-bao", displayName: "샤오롱바오", cuisine: "chinese", base: "other", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },

  { id: "m191", canonicalName: "cheese-hamburger", displayName: "치즈버거", cuisine: "western", base: "bread", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 3, priceRange: "low" },
  { id: "m192", canonicalName: "bacon-burger", displayName: "베이컨버거", cuisine: "western", base: "bread", hasSoup: false, protein: "pork", spicyLevel: 0, heavyLevel: 3, priceRange: "medium" },
  { id: "m193", canonicalName: "chicken-burger", displayName: "치킨버거", cuisine: "western", base: "bread", hasSoup: false, protein: "chicken", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m194", canonicalName: "fish-burger", displayName: "피쉬버거", cuisine: "western", base: "bread", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },

  { id: "m195", canonicalName: "croissant", displayName: "크로와상", cuisine: "western", base: "bread", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },
  { id: "m196", canonicalName: "danish", displayName: "데니쉬", cuisine: "western", base: "bread", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 1, priceRange: "low" },
  { id: "m197", canonicalName: "panini", displayName: "파니니", cuisine: "western", base: "bread", hasSoup: false, protein: "mixed", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },

  { id: "m198", canonicalName: "dumpling-soup", displayName: "만두국", cuisine: "korean", base: "noodle", hasSoup: true, protein: "pork", spicyLevel: 0, heavyLevel: 2, priceRange: "low" },
  { id: "m199", canonicalName: "tteokguk", displayName: "떡국", cuisine: "korean", base: "rice", hasSoup: true, protein: "beef", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m200", canonicalName: "tteok-manduguk", displayName: "떡만두국", cuisine: "korean", base: "rice", hasSoup: true, protein: "mixed", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },

  { id: "m201", canonicalName: "jangeo-gui", displayName: "장어구이", cuisine: "korean", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 3, priceRange: "high" },
  { id: "m202", canonicalName: "unagi-don", displayName: "장어덮밥", cuisine: "japanese", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "high" },
  { id: "m203", canonicalName: "salmon-don", displayName: "연어덮밥", cuisine: "japanese", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m204", canonicalName: "negitoro-don", displayName: "네기토로동", cuisine: "japanese", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "high" },

  { id: "m205", canonicalName: "garlic-shrimp", displayName: "갈릭쉬림프", cuisine: "western", base: "rice", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m206", canonicalName: "lobster", displayName: "랍스터", cuisine: "western", base: "other", hasSoup: false, protein: "seafood", spicyLevel: 0, heavyLevel: 3, priceRange: "high" },
  { id: "m207", canonicalName: "clam-chowder", displayName: "클램차우더", cuisine: "western", base: "bread", hasSoup: true, protein: "seafood", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },

  { id: "m208", canonicalName: "spaghetti-meat", displayName: "미트소스스파게티", cuisine: "western", base: "noodle", hasSoup: false, protein: "beef", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
  { id: "m209", canonicalName: "penne-arrabbiata", displayName: "아라비아따", cuisine: "western", base: "noodle", hasSoup: false, protein: "vegetarian", spicyLevel: 2, heavyLevel: 2, priceRange: "medium" },
  { id: "m210", canonicalName: "gnocchi", displayName: "뇨끼", cuisine: "western", base: "noodle", hasSoup: false, protein: "vegetarian", spicyLevel: 0, heavyLevel: 2, priceRange: "medium" },
];
